In [1]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9490, 0.3459, 0.7848, 0.2402],
        [0.0474, 0.5377, 0.1501, 0.4117],
        [0.4782, 0.8456, 0.2781, 0.7196]])

In [4]:
# Find out details about the tensor
print(some_tensor)
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Shape of tensor:  {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9490, 0.3459, 0.7848, 0.2402],
        [0.0474, 0.5377, 0.1501, 0.4117],
        [0.4782, 0.8456, 0.2781, 0.7196]])
Datatype of the tensor: torch.float32
Shape of tensor:  torch.Size([3, 4])
Device tensor is on: cpu


### Manupilating Tensors (operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication (Elementwise)
* Division
* Matrix Multiplication

In [5]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [6]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [7]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [8]:
# Built in mul functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [9]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

2 ways of doing multiplication: 
* elementwise 
* matrix multiplication (@ or 'torch.matmul()')

In [10]:
#Elementwise
print(tensor, '*', tensor)
tensor * tensor

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor([1, 4, 9])

In [11]:
%%time
# Matrix
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [12]:
%%time
# Matrix multiplication by hand
val = 0
for i in range(len(tensor)):
    val += tensor[i] * tensor[i]
print(val)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [13]:
# Transposing can be done by .T
tensorB = torch.rand(size=(3,2))
print ("Orignal tensor: \n", tensorB)
print("\nTensor transpose: \n", tensorB.T)

Orignal tensor: 
 tensor([[0.2698, 0.3393],
        [0.9117, 0.6107],
        [0.1558, 0.7764]])

Tensor transpose: 
 tensor([[0.2698, 0.9117, 0.1558],
        [0.3393, 0.6107, 0.7764]])


### Tensor Aggregation

Finding the:
* Min
* Max
* Mean
* Sum and so on

In [14]:
# Create a tensor

x= torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
torch.min(x), x.min()


(tensor(0), tensor(0))

In [16]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [17]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [18]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [19]:
# Returns position (index value) of min value.
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [20]:
# Returns position (index value) of max value.
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

### Reshaping, stacking and unstacking tensors
* Reshaping - reshapes and inputs tensors to a defined shape
* View - Returns a view of an input tensor of certain shape but keep the same memory as the orignal tensor
* Stacking - combine multiple tensors on top og each other (vstack) or sife by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Returns a view of the input with dimensions permuted (swapped) in a certain way

In [21]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [22]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [23]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [24]:
# Changing z changes x (because a view shares the same memory as the orignal).
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [25]:
# Stack tensors on top of each other.
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [26]:
# torch.squeeze() - removes all single dimesnions froma a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Removes extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(F"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}") 

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [27]:
# torch.peremute rearranges the dimesnions of a target tensor in a specified order.
x_orginal = torch.rand(size=(224, 224, 3)) # height, width,colour_channels

#Permute the orignal tensor to rearrange the axis (or dim) order
x_permuted = x_orginal.permute(2, 0, 1) # shifts the axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_orginal.shape}")
print(f"New Shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


In [28]:
x_orginal

tensor([[[0.8751, 0.9601, 0.9726],
         [0.5192, 0.9995, 0.1328],
         [0.6704, 0.4730, 0.6087],
         ...,
         [0.4299, 0.2787, 0.2349],
         [0.3240, 0.5001, 0.0015],
         [0.6582, 0.3441, 0.3451]],

        [[0.5362, 0.0644, 0.7074],
         [0.0167, 0.6703, 0.1500],
         [0.1136, 0.8952, 0.1865],
         ...,
         [0.1177, 0.4927, 0.6290],
         [0.8594, 0.2095, 0.1340],
         [0.7092, 0.0542, 0.2338]],

        [[0.2705, 0.7907, 0.6399],
         [0.8971, 0.7236, 0.6485],
         [0.9161, 0.6005, 0.1863],
         ...,
         [0.7941, 0.9128, 0.0979],
         [0.5161, 0.9778, 0.6048],
         [0.1329, 0.5449, 0.2222]],

        ...,

        [[0.4745, 0.9787, 0.7672],
         [0.3577, 0.9113, 0.2401],
         [0.6071, 0.2303, 0.6200],
         ...,
         [0.8207, 0.1970, 0.7752],
         [0.2663, 0.8569, 0.7224],
         [0.5841, 0.0496, 0.3003]],

        [[0.3819, 0.7509, 0.1472],
         [0.6817, 0.8863, 0.5096],
         [0.

In [29]:
x_orginal[0, 0, 0] = 0.1234
print(f"Orignal tensor: {x_orginal}")
print(f"Permuted tensor: {x_permuted}")

Orignal tensor: tensor([[[0.1234, 0.9601, 0.9726],
         [0.5192, 0.9995, 0.1328],
         [0.6704, 0.4730, 0.6087],
         ...,
         [0.4299, 0.2787, 0.2349],
         [0.3240, 0.5001, 0.0015],
         [0.6582, 0.3441, 0.3451]],

        [[0.5362, 0.0644, 0.7074],
         [0.0167, 0.6703, 0.1500],
         [0.1136, 0.8952, 0.1865],
         ...,
         [0.1177, 0.4927, 0.6290],
         [0.8594, 0.2095, 0.1340],
         [0.7092, 0.0542, 0.2338]],

        [[0.2705, 0.7907, 0.6399],
         [0.8971, 0.7236, 0.6485],
         [0.9161, 0.6005, 0.1863],
         ...,
         [0.7941, 0.9128, 0.0979],
         [0.5161, 0.9778, 0.6048],
         [0.1329, 0.5449, 0.2222]],

        ...,

        [[0.4745, 0.9787, 0.7672],
         [0.3577, 0.9113, 0.2401],
         [0.6071, 0.2303, 0.6200],
         ...,
         [0.8207, 0.1970, 0.7752],
         [0.2663, 0.8569, 0.7224],
         [0.5841, 0.0496, 0.3003]],

        [[0.3819, 0.7509, 0.1472],
         [0.6817, 0.8863, 0.509

### Indexing (selecting the data from tensors)
Indexing with pytorch is similar as numpy indexing


In [30]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [31]:
# Trying indexes of the tensor
print(x[0])
print(x[0, 0], x[0][0])
print(x[0, 0, 0], x[0][0][0])

#Getting element 9
print(x[0,2,2])

# All values of 0th and 1st dimensions but only index 1 of the second dimension
print(x[:, :, 1])

# All values of 0th but only index 1 of 1st and 2nd dimension
print(x[:, 1, 1])

# Get index 0 of 0th and 1st dimension and all values of the 2nd dimension
print(x[0, 0, :])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3]) tensor([1, 2, 3])
tensor(1) tensor(1)
tensor(9)
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])
tensor([[3, 6, 9]])


## PyTorch and NumPy

NumPy is a popular scientific Python numerical computing library.
PyTorch has functionality to interact with it.
* Data in numpy, wanted in pytorch sensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [32]:
# numpy array to tensor
array = np.arange(1.0, 8.0) # warning: default dtype of numpy is float 64, default dtype of torch tensors is float 32
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [33]:
# Change the value of array, what will this do to the `tensor`?
array = array + 1
array, tensor

# Note: nothing changes  

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [34]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = torch.Tensor.numpy(tensor)
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take a random out of random)
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> agian -> again -> again ...`

To reduce randomness in nn and PyTorch, random seed concept is used.
Essentially what the random seed does is 'flavour' the randomness.

In [35]:
# Create 2 random tensors
random_tensorA = torch.rand(3,4)
random_tensorB = torch.rand(3,4)

print(random_tensorA)
print(random_tensorB)
print(random_tensorA == random_tensorB)

tensor([[0.6111, 0.8523, 0.9069, 0.9601],
        [0.4905, 0.9368, 0.7343, 0.6194],
        [0.8698, 0.2298, 0.6398, 0.8342]])
tensor([[0.5393, 0.1521, 0.8402, 0.2277],
        [0.5587, 0.7882, 0.6096, 0.4627],
        [0.7216, 0.2557, 0.8020, 0.8951]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [36]:
# Making random but reproducable tensors

RANDOM_SEED = 42


torch.manual_seed(RANDOM_SEED)
random_tensorC = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensorD = torch.rand(3,4)

print(random_tensorC)
print(random_tensorD)
print(random_tensorC == random_tensorD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Utilizing GPU
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch
* Use Google collab
* Utilizing own GPU
* Use cloud computing - GCP, AWS, Azure 

Since PyTorch is capable on running both CPU and GPU, its a good practice to setup a device agnostic code, i.e use GPU if available else run on cpu `device = "cuda" if torch.cuda.is_available() else "cpu"`

In [37]:
!nvidia-smi

Sat Aug 12 17:23:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.78       Driver Version: 512.78       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   49C    P8     7W /  N/A |    556MiB /  4096MiB |     28%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [38]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

In [39]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Count number of devices
torch.cuda.device_count()

1

## Putting tensors and models on the GPU


In [40]:
# Create a tensor (default on CPU)

tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')


### Moving tensors back to cpu

NumPy only works on CPU

In [41]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)